{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 8,
			"minor" : 0,
			"revision" : 4,
			"architecture" : "x64",
			"modernui" : 1
		}
,
		"classnamespace" : "box",
		"rect" : [ 34.0, 78.0, 1082.0, 788.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"boxes" : [ 			{
				"box" : 				{
					"id" : "obj-8",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "bang", "int", "int" ],
					"patching_rect" : [ 52.0, 47.0, 83.0, 22.0 ],
					"text" : "live.thisdevice"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-6",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 52.0, 199.0, 51.0, 22.0 ],
					"text" : "receiver"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-10",
					"maxclass" : "newobj",
					"numinlets" : 2,
					"numoutlets" : 2,
					"outlettype" : [ "signal", "signal" ],
					"patching_rect" : [ 239.0, 483.0, 55.0, 22.0 ],
					"text" : "plugout~"
				}

			}
, 			{
				"box" : 				{
					"autosave" : 1,
					"bgmode" : 0,
					"border" : 0,
					"clickthrough" : 0,
					"id" : "obj-35",
					"maxclass" : "newobj",
					"numinlets" : 2,
					"numoutlets" : 8,
					"offset" : [ 0.0, 0.0 ],
					"outlettype" : [ "signal", "signal", "", "list", "int", "", "", "" ],
					"patching_rect" : [ 239.0, 401.0, 92.5, 22.0 ],
					"save" : [ "#N", "vst~", "loaduniqueid", 0, ";" ],
					"saved_attribute_attributes" : 					{
						"valueof" : 						{
							"parameter_invisible" : 1,
							"parameter_longname" : "vst~[1]",
							"parameter_shortname" : "vst~[1]",
							"parameter_type" : 3
						}

					}
,
					"saved_object_attributes" : 					{
						"parameter_enable" : 1,
						"parameter_mappable" : 0
					}
,
					"snapshot" : 					{
						"filetype" : "C74Snapshot",
						"version" : 2,
						"minorversion" : 0,
						"name" : "snapshotlist",
						"origin" : "vst~",
						"type" : "list",
						"subtype" : "Undefined",
						"embed" : 1,
						"snapshot" : 						{
							"pluginname" : "Equator.vst",
							"plugindisplayname" : "Equator",
							"pluginsavedname" : "/Library/Audio/Plug-Ins/VST/Equator.vst",
							"pluginsaveduniqueid" : 0,
							"version" : 1,
							"isbank" : 0,
							"isbase64" : 1,
							"blob" : "24488.CMlaKA....fQPMDZ....ATTbzIG...P2....A........................................7EaP.vQ+6GA..PuB..............................M2LVXhQyMwbSX4LFMlgyLhcCNyDyLzTyXy.SY1HCNjAPQQUUPT8jTeAkTEMUQTAP.DXWYxMWZu4F.AbPAw3RNt.C.0UWZjAP.hT.M2LVXhQyMwbSX4LFMlgyLhcCNyDyLzTyXy.SY1HCNjA.cgc1b.DfOE.UZg41arDzXuU2bzk1XrDDczE1XqwxTzIWcisFKBIWZmgFcrPTXxsFKRk1XnwxUgIWarb0auQFKRkzTEAvbuUmajQTZgwVRtQVY3AP.GTPKwvRKw.f.wDPSOQTSAQkTIgE..D.VC8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QAA0FbfTja1UFauAWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.D.DEDTavARQtYWYr8FbkoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNy.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QAA0FbfTja1UFauAWY5TC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.D.DEDTavARQtYWYr8FbkoiM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.UTvSyMVZrwVXz8lbfLzagI2bkoSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.UTvSyMVZrwVXz8lbfLzagI2bkoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.STvSyMVZrwVXz8lbfXTZtUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.ALQAOM2XowFagQ2axAhQo4VY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DvDE7zbikFarEFcuIGHFklakoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.RTvTg0FbrUlbfLzagI2bkoCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTvTg0FbrUlbfXTZtUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.AHQASEVavwVYxAxPuElbyUlNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QASEVavwVYxAhQo4VY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPDELUXsAGakIGHLUlckwlNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxnCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAhL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfHiNx.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxnyL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAhL5PC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfHiN0.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxniM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNz.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.AjQASEVavwVYxAhQowFckIGHCUGcuYlY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPFELUXsAGakIGHFkFazUlbfLTcz8lYloSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.OTfSuk1bkABSkYWYroCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfLiNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHyniL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5LC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfLiNz.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHynSM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5XC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5.C.2UVZmgFc.DfAE.iKxTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5.C.2UVZmgFc.DfAE.iKxTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DvCELUXsAGakIGHPEla5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkARL5.C.jU1bzAP.YTvTg0FbrUlbfXTZrQWYxAxP0Q2alYlNv.vckk1YnQG.AfQAv3xMwDSLwDSLxfyLy.iLy.yMwHCN4.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AvPASQmbosVYfDiNv..YkMGc.D.DEDTavARQtYWYr8FbkoCM.bWYocFZzAP.XT.LtjiLxHiLxHSM1XiMvPiMwPiL0bCN.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.LTvTzIWZqUFHxnCL.PVYyQG.AjQASEVavwVYxAhQowFckIGHCUGcuYlY5DC.2UVZmgFc.D.FE.iK2HiLxHiLxXCN0fSLyjCLyfCL3XC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkAxL5.C.jU1bzAP.NTPQtYWYr8FbkAhL5PC.2UVZmgFc.D.FE.iKzbyM2byM2bSNw.iLyHSMzLSNzTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkABM5.C.jU1bzAP.STfQowFckIGHw.xP0Q2alYlNv.vckk1YnQG.AfQAv3RM0TSM0TSM3HCLzXSMvfyM3jCL1.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAKUVdzIWXisVZtcFHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTvRkkGcxE1XqklamAhL5.C.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DfDELUXsAGakIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DfDELUXsAGakIGHC8VXxMWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5PC.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNz..YkMGc.DPDELUXsAGakIGHLUlckwlNw.vckk1YnQG.AfQAv3hLxHiLxHiLxLCN2bSNvXyM4jyLx.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNz..YkMGc.D.DEDTavARQtYWYr8FbkoCL.bWYocFZzAP.XT.LtPyM2byM2byM4DCLxLiL0PyL4PSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCM.PVYyQG.A3PAE4lckw1avUFHxnCL.bWYocFZzAP.XT.LtPyM2byM2byM4DCLxLiL0PyL4PSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCM.PVYyQG.A.QAA0FbfTja1UFauAWY5LC.2UVZmgFc.D.FE.iK1DSLwDSLwXCMvjyLvDyM0bCNwHC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5PC.jU1bzAP.NTPQtYWYr8FbkAhL5LC.2UVZmgFc.D.FE.iK2.CLv.CLvPyM1fyL2DSM3HCLyDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QkwVX4ABSkYWYrABSkYFc5.C.2UVZmgFc.D.FE.iK0byM2byM3.iL4PCMwfyLyPSN1DC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.WT.QkwVX4AhQkUFYhE1XqABSkYFc5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.D.FEPTYrEVdfXTYkQlXgM1ZfHUZmgFc5.C.2UVZmgFc.D.FE.iKwHiLxHiLxHiLyfyM2jCL1bSN4LC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.UT.QkwVX4ABSkYWYrAhTocFZzoCL.bWYocFZzAP.XT.LtTiLxHiLxHiLvfSN2XyMzTiMvTSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.A.QACg1axU2bfbUZjQGZ5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5.C.jU1bzAP.NTvPn8lb0MGHWUFc5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5.C.jU1bzAP.PTvPn8lb0MGHSAWYkQlNv.vckk1YnQG.AfQAv3xL3fCN3fCN4TSMwDiMxbSL4biL2.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNw..YkMGc.DPBEvjQOAhL5DC.2UVZmgFc.DvEE.iK1HiLxHiLxPCM2LSN0LiLzbCL2.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNw..YkMGc.DPBEvjQOARL5DC.2UVZmgFc.D.FE.iK2LyLyLyLyPSNxHyM4.SMxbyLzPC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5DC.jU1bzAP.IT.SF8DHwnCL.bWYocFZzAP.ZTPKv3BLzDiM1XiM1bSNvfCMy.CL4jCM3bC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5HC.jU1bzAP.PTPPsAGHE4lckw1avUlNy.vckk1YnQG.AfQAv3hM0TSM0TSMzXiL3LyMxDSNxLCNy.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNx..YkMGc.DfCETja1UFauAWYfHiNy.vckk1YnQG.AfQAv3xMwDSLwDSLxfyLy.iLy.yMwHCN4.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.DvDEPTZyQ2axQWZu4FHFUmd5oCL.bWYocFZzAP.WT.LtDCN3fCN3fSNxTyLwLSNzjSM3TC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QoMGcuIGco8lafHDak4FY5.C.2UVZmgFc.D.FE.iK2TSM0TSM0bCLwHSM0bSN3LyL4fC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QoMGcuIGco8lafPjboYWY5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.DvDEPTZyQ2axQWZu4FHT8lakoCL.bWYocFZzAP.XT.LtHiLxHiLxHiLyfyM2jCL1bSN4LiL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoyL.PVYyQG.APQADk1bz8lbzk1atABSkYWYroCL.bWYocFZzAP.XTPKv3hL3fCN3fSNvDCM2HCL4DiM2PCN.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.ADQASEVavwVYxABSkYWYroCL.bWYocFZzAP.XTPKv3RLzPCMzPCM0.yMyXCLzTCNybCM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.XTPKv3RLzPCMzPCM0.yMyXCLzTCNybCM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.PTPPsAGHE4lckw1avUlNv..YkMGc.D.EE7zbikFarEFcuIGHLUlckwlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.A.QAA0FbfTja1UFauAWY5.C.jU1bzAP.TTvSyMVZrwVXz8lbfvTY1UFa5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.DEDTavARQtYWYr8FbkoCL.PVYyQG.APQAOM2XowFagQ2axABSkYWYroiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.PTPPsAGHE4lckw1avUlNv..YkMGc.DPDELUXsAGakIGHLUlckwlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.A3PAE4lckw1avUFHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.IT.SF8DHwnCL.PVYyQG.A7PASEVavwVYxABTg4lNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPALYzSfDiNv..YkMGc.DvCELUXsAGakIGHPEla5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEvjQOAhL5.C.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5.C.2UVZmgFc.DPFEzBLtfiLxHiLxHyLxfSL3XCLyTSL0XiL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.IT.SF8DHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.YTPKv3BNzPCMzPCM0LyMwXiL2fCL2XSL2.PagAGbo41Y.Dv.E.C..rTQYQkTAMzRI4zQ.DP.s8FYkAP.CTPL.DvAN8DQEAP.B.WZzMFZ.Dv.E.C.g01a04Fc.D.FE.iKzbCLyLCN4bCLzHiL2PCM2TCL4fC..3zSDUD.AH.boQ2XnAP.XT.LtHSNyPSM3LyMxLSMzTCL2PCM1HSN.DVauUmazAP.WT.LtLiM3XCMz.SM3bCLzLyM1HiLvbC..3zSDUD.AH.boQ2XnAP.XT.LtLiL3XCNxTSLx.CMzjCL1XSL1HSL.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AbQAv3RM3XiLy.SM2XCLyfyL1.SM4TyM.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AfQAv3hMxTSM2DCNzXSN1DSN2TCL4biM1.PXs8VctQG.AfQAv3RMzXiMw.SL2XSM1LiL1HSNyjCM0...N8DQEAP.B.WZzMFZ.D.FE.iK1byM2HSL3TCNvHCM0jyMwXyM4bC.g01a04Fc.Dv.EDC..3zSDUD.AH.boQ2XnAP.CTPL.DVauUmazAP.CTPL...TAIUPMAP.BjFY.D.CE7zTCARLLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.JTvSSMDHw.UXtAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCE7zTCARLFkFazUlbfDC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.OTvSSMDHwXTZrQWYxAhL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjPAOM0PfDiQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPCE7zTCARLRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AnPAOM0PfDCQxkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvSSMDHwbUX1UlYuIWa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A3PAOM0PfDSQtElXrUFY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAOM0PfDyPuElbyUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KTvSSMDHwXTZtUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTvSSMDHw.UcrMWYWkFYzgF.1EFa0UF.AXPAv3hL0...PEjTA0D.AHPZjAP.LTvSSMDHxvTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AnPAOM0PfHCTg4F.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvSSMDHxXTZrQWYxARL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A7PAOM0PfHiQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DPBE7zTCAhLFgE.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.MTvSSMDHxHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfBE7zTCAhLDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAOM0PfHyUgYWYl8lbsAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfCE7zTCAhLE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPCE7zTCAhLC8VXxMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ArPAOM0PfHiQo4VY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAOM0PfHCT0w1bkcUZjQGZ.XWXrUWY.DfAE.iKxTC...UPRETS.Df.oQF.AvPAOM0PfLCSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfBE7zTCAxLPEla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAOM0PfLiQowFckIGHw.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvCE7zTCAxLFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ITvSSMDHyXDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAOM0PfLiTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.JTvSSMDHyPjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCE7zTCAxLWElckY1ax0F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.NTvSSMDHyTjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.MTvSSMDHyLzagI2bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvBE7zTCAxLFklakAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDE7zTCAxLPUGayU1UoQFcnAfcgwVckAP.FT.LtHSM...TAIUPMAP.BjFY.DvBEXTSE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDEHUZtcVSuQlQowFckIGHw.fcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDEHUZtcVSuQlQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvBEHUZtcVSuQlQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCEHUZtcVSuQlTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfTo41YM8FYDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQASEVavwVYxARLE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.DELUXsAGakIGHwvTY1UFa.XWXrUWY.D.FE.iK1HyMwTSNxjyMzXiMxbCNvbiMwbC...UPRETS.Df.oQF.A3PASEVavwVYxARLPEla.XWXrUWY.DPFE.iKvPiMxfSNvfiMyPSL3TyM4DCLwTiM...TAIUPMAP.BjFY.DPDELUXsAGakIGHw7jYlMWYzAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDELUXsAGakIGHwXTZrQWYxARL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQASEVavwVYxARLFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.MTvTg0FbrUlbfDiQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDELUXsAGakIGHwHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCELUXsAGakIGHwPjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDELUXsAGakIGHwLzagI2bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCELUXsAGakIGHwXTZtUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTvTg0FbrUlbfHSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A.QASEVavwVYxAhLLUlckwF.1EFa0UF.AzPAv3xM1bSM2fSLxTC...UPRETS.Df.oQF.A3PASEVavwVYxAhLPEla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLOYlYyUFc.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQASEVavwVYxAhLFkFazUlbfDC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.STvTg0FbrUlbfHiQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DPCELUXsAGakIGHxXDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A3PASEVavwVYxAhLDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLC8VXxMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PASEVavwVYxAhLFklakAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCE3zaoMWYE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CE3zaoMWYWkFYzgF.1EFa0UF.AfQAv3hL3TCN0.yMvLyMwXiL2fCL2XSL2...PEjTA0D.AHPZjAP.LTfSuk1bkwTY1UFa.XWXrUWY.D.FE.iK4.iLzbyL4fiMwPCN3LCMxHCN0HC...UPRETS.Df.oQF.A7PAN8VZyUlQowFckIGHw.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvCE3zaoMWYFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ITfSuk1bkYDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAN8VZyUlTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.JTfSuk1bkQjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCEXTZrQWYxARLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPDEXTZrQWYxARLE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.DEXTZrQWYxARLCUGcOYlY.XWXrUWY.D.FE.iK4.SNxPCM2DiMwXyMzPSN4TSLwbC...UPRETS.Df.oQF.ALQAFkFazUlbfDiTkM2atElaiUF.1EFa0UF.AjQAv3BL3biM2LyLxfCNwXCN4.yMwXSM0LC...UPRETS.Df.oQF.ALQAFkFazUlbfDyPu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEXTZrQWYxARLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfEEXTZrQWYxARLC8VahYTYkQlXgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A3PAFkFazUlbfHCU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAFkFazUlbfHSQtElXrUFY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAFkFazUlbfHyP0Q2SlYF.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DvDEXTZrQWYxAhLRU1bu4VXtMVY.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.ALQAFkFazUlbfHyPu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEXTZrQWYxAhLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfEEXTZrQWYxAhLC8VahYTYkQlXgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAN8VZyUFHFkFazUlbTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPEE3zaoMWYfXTZrQWYxUjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.TTfSuk1bkAhQowFckI2P0Q2SlYF.1EFa0UF.AfQAv3BN4HSN1fyMwPiLybiLwLSLyPyM2...PEjTA0D.AHPZjAP.WTfSuk1bkAhQowFckImTkM2atElaiUF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.WTfSuk1bkAhQowFckI2Pu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPEE3zaoMWYfXTZrQWYxMzasIVSogG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.ZTfSuk1bkAhQowFckI2Pu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.VTvTg0FbrUlbfXTZrQWYxARLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPFELUXsAGakIGHFkFazUlbfDSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AfQASEVavwVYxAhQowFckIGHwLTcz8jYlAfcgwVckAP.XT.LtLyM4fSL2XSNzPiL0TCNxfCN0bCM...TAIUPMAP.BjFY.DvFELUXsAGakIGHFkFazUlbfDiTkM2atElaiUF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.aTvTg0FbrUlbfXTZrQWYxARLC8VahQTYrEVd.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.YTvTg0FbrUlbfXTZrQWYxARLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfGELUXsAGakIGHFkFazUlbfDyPu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.VTvTg0FbrUlbfXTZrQWYxAhLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPFELUXsAGakIGHFkFazUlbfHSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AfQASEVavwVYxAhQowFckIGHxLTcz8jYlAfcgwVckAP.XT.LtfCM1DCNvTSM3HCLzXSMvfyM3jSL...TAIUPMAP.BjFY.DvFELUXsAGakIGHFkFazUlbfHiTkM2atElaiUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.aTvTg0FbrUlbfXTZrQWYxAhLC8VahQTYrEVd.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.YTvTg0FbrUlbfXTZrQWYxAhLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfGELUXsAGakIGHFkFazUlbfHyPu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.NT.QkwVX4UjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.KT.QkwVX4wTYlQG.1EFa0UF.AfQAv3RL2TCLv.CLwDSNx.SNxfSN0TCL3...PEjTA0D.AHPZjAP.LT.QkwVX4IUZmgFc.XWXrUWY.D.FE.iKyTCLv.CLvHyL3PSL3TyM4DCLwXC...UPRETS.Df.oQF.A3PAFUVYjIVXisFSkYFc.XWXrUWY.D.FE.iKzHiMwbSL2HCLvHyM4HyL0fyL4fC...UPRETS.Df.oQF.A7PAFUVYjIVXislTocFZzAfcgwVckAP.XT.LtHyMzLCL0TCNx.CM1TCL3bCN4.iM...TAIUPMAP.BjFY.DvBEvTY1UFaLUlYzAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CEvTY1UFaRk1YnQG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvPn8lb0MWQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A3PACg1axU2bfLEbkUFY.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.A7PACg1axU2bfDTauUmazAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCELDZuIWcyAxUoQFcnAfcgwVckAP.ET.LtTC...UPRETS.Df.oQF.A3PACg1axU2bfPTYvQGZ.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A7PARUlckImXE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.CEHUY1UlbhAxUkQG.1EFa0UF.AjQAv3BL1PCNv.yLzPCMvbSM0fCMzDSL1HC...UPRETS.Df.oQF.AHQARUlckImXf.kbkABQkwVX4AfcgwVckAP.XT.LtDCM0bCN4jyL1DCNzfCNyDSL2XCN...TAIUPMAP.BjFY.D.DEHUY1UlbhABQg0Fbo41Y.XWXrUWY.D.FE.iK2fCLzXCN2XSL4HCL4HCN4TSMvfC...UPRETS.Df.oQF.AzPARUlckImXfLUZ5UF.1EFa0UF.AfQAv3RM1LyL1fCL3HCLzXSMvfyM3jCL1...PEjTA0D.AHPZjAP.KTPQQUjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGHw.fcgwVckAP.XT.LtDiM1XiM1XyMwXyLybiLvLSN2jSM...TAIUPMAP.BjFY.DvBETTTfbTXo4FHw.fcgwVckAP.CT.L...TAIUPMAP.BjFY.D.BETTTfDEHw.fcgwVckAP.XT.LtDSMv.CLv.CL0jiMvPiMzPyM2TCM...TAIUPMAP.BjFY.D.DETTTfXjbkEWck41X4AhL.XWXrUWY.DvEE.iKyLyLyLyLyPyLxXyMzPCL2jSM4...PEjTA0D.AHPZjAP.KTPQQAxQgklafHC.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.HTPQQARTfHC.1EFa0UF.AfQAv3RL0.CLv.CLvTSN1.CM1PCM2bSMz...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGHy.fcgwVckAP.XT.LtjCLxLSNvPiLvPyL1fSM4DyLvfiM...TAIUPMAP.BjFY.DvBETTTfbTXo4FHy.fcgwVckAP.YTPKv3hLvHyMvHyMvDCL4DyM1XyL0bCMx...PEjTA0D.AHPZjAP.HTPQQARTfLC.1EFa0UF.AfQAv3BMzDSM1HSMvLSM2XiL2fiM3XSMx...PEjTA0D.AHPZjAP.OT.SF8DHw.0arElboQWd.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A.QALYzSfDyUgYWYSgVXvUF.1EFa0UF.ALPAz...PEjTA0D.AHPZjAP.LT.SF8DHwvTY1UFa.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QALYzSfDiQxUVb0UlaikG.1EFa0UF.AjQAv3BL3fyLzXCMvXCNwbCMyXiLwfiL1HC...UPRETS.Df.oQF.A3PALYzSfDCUxk1YmUlb.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ArPALYzSfDiQgQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PALYzSfHCTuwVXxkFc4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEvjQOAhLWElckMEZgAWY.XWXrUWY.Dv.EPC...UPRETS.Df.oQF.AvPALYzSfHCSkYWYrAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEvjQOAhLFIWYwUWYtMVd.XWXrUWY.D.FE.iKwLyLyLyLyPCLxfyMx.CN0TyMwLC...UPRETS.Df.oQF.A3PALYzSfHCUxk1YmUlb.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ArPALYzSfHiQgQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AfQAA0FbfTja1UFauAWYRUFbkEFcTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.EEDTavARQtYWYr8FbkEDczE1XqAfcgwVckAP.YT.Lt.iL2DCLvLCLvPSL1LSMvLiMzXCN0...PEjTA0D.AHPZjAP.STPPsAGHE4lckw1avUFQkMVX4AfcgwVckAP.XT.LtbyL4TiM1TCLzjSM0HSNwbCM3.SM...TAIUPMAP.BjFY.DPEEDTavARQtYWYr8FbkMUcyQWXo4F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.UTPPsAGHE4lckw1avUlTkwVYgMWY.XWXrUWY.D.FE.iKxHSN2bSMxjCM1XSL0HSL4DSL1HC...UPRETS.Df.oQF.ALQAA0FbfTja1UFauAWYLUlckwF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.aTPPsAGHE4lckw1avUFTrU2Xq8jYlwTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ArQAA0FbfTja1UFauAWYPwVcis1SlY1UoQFcnAfcgwVckAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TAIUPMAP.BjFY.DfEETja1UFauAWYfHiTkAWYgQGU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAE4lckw1avUFHxDDczE1XqAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfHCQkMVX4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDETja1UFauAWYfHyT0MGcgkla.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQAE4lckw1avUFHxHUYrUVXyUF.1EFa0UF.AfQAv3RL3DiL0.SL1jCN2LiLybiMvjCN1...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkAhLLUlckwF.1EFa0UF.AfQAv3hLwHiMy.iLwHyLvXSN2XyLwfyL1...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkAhLPwVcis1SlYFSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfHCTrU2Xq8jYlcUZjQGZ.XWXrUWY.DPFE.iKvjSN4jSN4PSL3fSMzbSLyPyL4jCM...TAIUPMAP.BjFY.DfEETja1UFauAWYfLiTkAWYgQGU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAE4lckw1avUFHyDDczE1XqAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfLCQkMVX4AfcgwVckAP.XT.LtDCLzbCL2DCNwPSMybCLzfyLyjCN...TAIUPMAP.BjFY.DvDETja1UFauAWYfLyT0MGcgkla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQAE4lckw1avUFHyHUYrUVXyUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkAxLLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkAxLPwVcis1SlYFSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfLCTrU2Xq8jYlcUZjQGZ.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.AXQAE4lckw1avUFHzHUYvUVXzQUdvUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTPQtYWYr8FbkABMAQGcgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAE4lckw1avUFHzPTYiEVd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQAE4lckw1avUFHzLUcyQWXo4F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.STPQtYWYr8FbkABMRUFakE1bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfPCSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfPCTrU2Xq8jYlwTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjQAE4lckw1avUFHz.Ea0M1ZOYlYWkFYzgF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.VTPQtYWYr8FbkARMRUFbkEFcTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDETja1UFauAWYfTSPzQWXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkARMDU1XgkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.STPQtYWYr8FbkARMSU2bzEVZtAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DvDETja1UFauAWYfTiTkwVYgMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAE4lckw1avUFH0vTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjQAE4lckw1avUFH0.Ea0M1ZOYlYLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkARMPwVcis1SlY1UoQFcnAfcgwVckAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TAIUPMAP.BjFY.D.GEXTZrQWYxAhPr81XqAxPu4lYocVcxEFco8la.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAI4Fb0QGHw.BcuAhQXAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DvDEjjavUGcfDCHz8FHRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAI4Fb0QGHw.BcuABQxkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTPRtAWczAhLfP2afXDV.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.STPRtAWczAhLfP2afHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEjjavUGcfHCHz8FHDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAF0DHC8lalk1Y0IWXzk1atAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CEXTSfPTYvQGZfDD.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfQMABQkAGcnAhP.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAPIWYyMWcxUFHMEFbvklamAxPuUlY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ATQASQmbosVYfzTXvAWZtcFHC8VYlAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPFE.UZzMFZfHTYtQFHMEFbvklamAxPuUlY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAEEEHFIWYwUWYtMVdfPC.1EFa0UF.Aj.A....fUUUk+C.PEjTA0D.AHPZjAP.KTPQQAxQgklafPC.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.HTPQQARTfPC.1EFa0UF.AfQAv3hLv.CLv.CLvHSN3.iLyHiLyfyM2...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGH0.fcgwVckAP.XT.LtbCN4TCL3XCMvbiM1DCMybSN3fyL...TAIUPMAP.BjFY.DvBETTTfbTXo4FH0.fcgwVckAP.XT.LtDyM0XyM0XyLvTiM4PSM3.CL2fSL...TAIUPMAP.BjFY.D.BETTTfDEH0.fcgwVckAP.YT.Lt.SNxjiL4XSNw.yM1HyM3XCN1TiLy...PEjTA0D.AHPZjAP.STPRtAWczARLfP2af7TczAWczAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDEjjavUGcfHCHz8FHOUGcvUGc.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQAOUGcvUGcfbVXo4FHz8FHFgE.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.WTvS0QGb0QGHmEVZtABcuAhTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.TTvS0QGb0QGHmEVZtABcuABQxkG.1EFa0UF.ALPAv...PEjTA0D.ADPZjAP.ST.SoYFcfzTXvAWZtcFHC8VYlA..PEjTA0D.ADPZjAP.YT.TxU1byUmbkARSgAGbo41YfLzakYFHx...PEjTA0D.ADPZjAP.WTvTzIWZqUFHMEFbvklamAxPuUlYfHC...UPRETS.DP.oQF.ATQALklYzARSgAGbo41YfLzakYFHx...PEjTA0D.ADPZjAP.aT.ToQ2XnAhPk4FYfzTXvAWZtcFHC8VYlAhL...TAIUPMAP.AjFY.DPFE.kbkM2b0IWYfzTXvAWZtcFHC8VYlAxL...TAIUPMAP.AjFY.DvEELEcxk1ZkARSgAGbo41YfLzakYFHy...PEjTA0D.ADPZjAP.UT.SoYFcfzTXvAWZtcFHC8VYlAxL...TAIUPMAP.AjFY.DvFE.UZzMFZfHTYtQFHMEFbvklamAxPuUlYfLC...UPRETS.DP.oQF.AjQAPIWYyMWcxUFHMEFbvklamAxPuUlYfPC...UPRETS.DP.oQF.AbQASQmbosVYfzTXvAWZtcFHC8VYlABM...TAIUPMAP.AjFY.DPEEvTZlQGHMEFbvklamAxPuUlYfPC...UPRETS.DP.oQF.ArQAPkFcigFHBUlajARSgAGbo41YfLzakYFHz...PEjTA0D.AHPZjAP.NTvSiQWX1UFHSgVZlQG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfUuk1XkARSuQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QARklam0zajUjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTfSuk1bkcUX1UlYuIWa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQABkFciIWcygVYxUjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTfPoQ2XxU2bnUlbfPjboYWY.XWXrUWY.D.FE.iKxDCMwjiL2.yLyXiMxbSN1.iLvTC...UPRETS.Df.oQF.AHQABkFciIWcygVYxAxPxU2bnAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDEHTZzMlb0MGZkIGHRUFY0MVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQABkFciIWcygVYxABUu4VY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AHQABkFciIWcygVYxAhPrUlajAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDEHTZzMlb0MGZkIGHLUlckwF.1EFa0UF.AfQAv3RM1PyM0XSNxjCN2PCMx.SL1XCLx...PEjTA0D.AHPZjAP.ST.QoMGcuIGco8laE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfDEPTZyQ2axQWZu4FHDIWZ1UF.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEPTZyQ2axQWZu4FHBE1byAfcgwVckAP.ET.LtTC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atABUu4VY.XWXrUWY.D.FE.iKxTSMyfSL4PSL2jSMyPSNwHSLvjC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atAhQ0omd.XWXrUWY.D.FE.iKyDiM4TSN1PSNyHCMzDyMwDCMxXC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atAhPoQWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQADk1bz8lbzk1atAhPrUlajAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDEPTZyQ2axQWZu4FHLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ZTPPsAGHE4lckw1avUVPzQWXisFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.YTPPsAGHE4lckw1avUFQkMVX4AxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvFEDTavARQtYWYr8FbkIUYrUVXyUFHSw1avUF.1EFa0UF.AjQAs.iKwTSM0TSM0PiMxfyL2HSL4HyL3LC...UPRETS.Df.oQF.AfQAE4lckw1avUFHxDDczE1XqAxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvEETja1UFauAWYfHCQkMVX4AxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPFETja1UFauAWYfHiTkwVYgMWYfLEauAWY.XWXrUWY.DPFEzBLtHCMzPCMzPiL4fyMzPiLvDiM1.iL...TAIUPMAP.BjFY.D.FETja1UFauAWYfLSPzQWXisFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.WTPQtYWYr8FbkAxLDU1XgkGHSw1avUF.1EFa0UF.AjQAs.iKzHSM0LSL4HyL2bCL4.CM0PSLvHC...UPRETS.Df.oQF.AjQAE4lckw1avUFHyHUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQtYWYr8FbkABMAQGcgM1ZfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAE4lckw1avUFHzPTYiEVdfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AjQAE4lckw1avUFHzHUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQtYWYr8FbkARMAQGcgM1ZfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAE4lckw1avUFH0PTYiEVdfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AjQAE4lckw1avUFH0HUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KT.UxElayA2ayUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KTfQo4VYfPUctUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQlYVYiQGHM8FY0wVXzk1atARSuQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAPIWYyUFcLUlckwF.1EFa0UF.AfQAv3RL4LSL0XCM1TCN3fCLxLyL2XCM1...KUTVTIUPCsTRNcjL.DP.s8FYkAP.CTfL.D.AN8DQEAP.B.WZzMFZ.Dv.E.C.g01a04Fc.Dv.EDC..3zSDUD.AH.boQ2XnAP.XT.LtPCMvLCNvDCN0fCMxTSLz.yL3.SN.DVauUmazAP.CTPL..fSOQTQ.Df.vkFcigF.AfQAv3BM1TyMxTCNvjyLyTyMvfiMwfSL1.PXs8VctQG.AfQAv3RM4DSN0PCL0HCMzfiL2HyMvTCL3...N8DQEAP.B.WZzMFZ.Dv.EDC.g01a04Fc.D.FE.iK0fCLzTSN2byL0PCLzjiM3HiMwbC..rTQYQkTAMzRI4zQy....rTQYQkTAMzRI4zQz.P.Az1ajUF.ALPAx.P.C3zSDUD.AH.boQ2XnAP.CT.L.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AjQAv3BLxLCMvLCL3LSNvTSM2biM0jiMvbC.g01a04Fc.Dv.E.C..3zSDUD.AH.boQ2XnAP.CTPL.DVauUmazAP.CTPL..vTTIURKUDL..P.C.0ao4Fc.Dv.XAP.CT.L.jE.ALPAv.vPuUlYlk1XoUlazAP.CT.L...TuklazAP.CfE.AfQAv3RLxLyM3XCMvPyMxfCN3jCM1TyLy.PV.Dv.E.C.C8VYlYVZikVYtQG.AfQAv3hLzHiM2XCLzjCM2.SNvDCM3jiL1...P8VZtQG.AH.V.Dv.EDC.YAP.CTPL..vTTIURKUTL..P.C.0ao4Fc.Dv.XAP.CT.L.jE.ALPAv.vPuUlYlk1XoUlazAP.CT.L...TuklazAP.CfE.AfQAv3BNwbSN1DSL0XyL1fiL0TiMwTiLy.PV.D.FE.iK2byMzfiM4HCLyTiM2TCLzfCNxfC.C8VYlYVZikVYtQG.AfQAv3BM2jSN4jSN3jiL2DSL1LSNz.CMy...P8VZtQG.AL.V.Dv.EDC.YAP.CTPL.LzakYlYoMVZk4Fc.D.FE.iKzbSN4jSN4fSNxbSLwXyL4PCLzLC..LEURkzREIC..Dv.P8VZtQG.AL.V.Dv.E.C.YAP.CT.L.LzakYlYoMVZk4Fc.D.FE.iKx.CLv.CLv.iL4fCLxLiLxLCN2bC...0ao4Fc.Dv.XAP.XT.LtXiMxXiLwLyM3fSN3XiLvXCL0PyM.jE.AfQAv3xM1bCLwTiM4TSM2DCN4jCMwPCL1.vPuUlYlk1XoUlazAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TuklazAP.BfE.ALPAw.PV.D.FE.iKvDyLvfSNv.CM4.CMvLSL2TyL0PC..LEURkzREMC...fPE4DQv....HTQNQTL....BUjSDIC...fPE4DQy....HURSUTVv....HURSUTVw....HURSUTVx....HURSUTVy.....kTEM0Tv.....kTEM0Tw.....kTEM0Tx.....kTEM0Ty....vTRFQEL....LkjQTEC....SIYDUx....vTRFQ0L....ME1Xx8FUuEDaoE1bSQWXzUF..DPAMEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNv.PPrkVXykDQ.DPDEHURSUDHLUlYzAhQgQVYxA..MEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNw.PPrkVXykDQ.DvDEHURSUDHMkFYjwVYfXTXjUlb..PSAAETI4zQ.Df.ME1Xx8VRDAP.ITPSgMlbuoiL.DDaoE1bIQD.AHQARkzTEAhTocFZzAhQgQVYxA..MEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNy.PPrkVXykDQ.DPEEHURSUDHPEFYffzaxkldu4FcgwF..zTPPAURNcD.AHPSgMlbukDQ.DPBEzTXiI2a5PC.AwVZgMWRDAP.STfTIMUQf.UXjAhUkIGcoMVXrA..ME1Xx8lUgwVckMG..DPAME1Xx8lNv.P.AXUXrUWY.Dv.E.C..zTXiI2a5DC.ADfUgwVckAP.CT.L..PSgMlbuoiL.DP.VEFa0UF.ALPAv...ME1Xx8lNy.P.AXUXrUWY.Dv.E.C..zTXiI2a5PC.ADfUgwVckAP.CT.L..vTA0DTLUjT..P.BzzajUGak8EL..P.AjjayQmb00VYtQG.AHPUUkDQ.DfIEfSMvDCYgYFYsXiXzLSKzHFLk0RNyXCMsD1MvjSYjgSMkcSY3.fSg0VY.DPDEjDcgwVZg41QxElajAhYlA..M8FY0wVYeEC..DP.I41bzIWcsUlazAP.BTUUIQD.AXRA3TyMlQCMhIVKgMSXxzBMlMVLsHFYzPSKzDVMhQlYwDlXlMyL.3TXsUF.ADQAIQWXrkVXtcjbg4FYfzlY...TAIUPMAP.BjFY.DPDELUXsAGakIGHw.kbkMWYzAfcgwVckAP.IP.............TAIUPMAP.BjFY.DPDELUXsAGakIGHx.kbkMWYzAfcgwVckAP.IP.............TAIUPMAP.BjFY.DPEEPTYrEVdBAUSSkmaiUjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.WT.SF8DHwHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.WT.SF8DHxHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.dTPPsAGHE4lckw1avUlPP0DHSkmaiARQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.AvQAE4lckw1avUFHxHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.bTPQtYWYr8FbkAxLBAUSfLUdtMFHE4VXhwVYjAfcgwVckAP.IP.............TAIUPMAP.BjFY.D.GETja1UFauAWYfPiPP0DHSkmaiARQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.AvQAE4lckw1avUFH0HDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............T8VcigFQo0VYtMWZu41bC8lalk1Y0IWXzk1atA..ADvTk41boQWZ1kFcoU1b..P.ELEcxk1ZkAP.AXUXrUWY.Dv.EDC..bDaoQVY.DP.VEFa0UF.ALPAv...SwVZjUF.ADfUgwVckAP.CTPL...TxU1byAP.AXUXrUWY.Dv.EDC..vTZlQG.ADfUgwVckAP.CTPL...TAIUPMAP.BjFY.DPJELEaoQVYfDjXy8Fa0QWYfP0afHUYrEFcoYWYfzzajUFHE4VXhwVYjAfcgwVckAP.IP.........7+..TAIUPMAP.BjFY.DfDE.kbkMWYzABTuwVdvg1atkG.1EFa0UF.Aj.A........v.D.PEjTA0D.AHPZjAP.OT.SRwTZtsVQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.A7QAM8lauAhUuk1XkABTx81XkM2bo41YfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.aTPSu41afX0aoMVYf.kbuMVYyMWZtcFHPEla.XWXrUWY.DPBD.........9O.zTXiI2aT81Pu4Fcx8FaMEFbvklamMG...PSPUzPu4lYocVcxEFco8la..P.JzDTEUjagIFakQF.ADfUgwVckAP.AH..MAUQME1bzUlbCgVXt4VYrAP.AXUXrUWY.DPAAD......MAUQNUWaN8FckMDZg4lakw1b.DP.VEFa0UF.ATP.O.....PSPUDTkImSuQWYPIjTg41YkAP.AXUXrUWY.DPAA.C.....MAUQME1bzUlbPIjTg41YkAP.AXUXrUWY.DPAAH......LU1YgMVdM8FYk0TcrQWZE4VXhwVYjAP.AXUXrUWY.DP.B..SkcVXikWSuQVYSklamwVY.DP.VEFa0UF.ATP.A......SkcVXikWSuQVYFklbyQ2PnElatUFa.DP.VEFa0UF.ATP.A......SkcVXikWSuQVYLE1bzMDZg4lakwF.ADfUgwVckAP.ED.D.....vTYmE1X40zajUFToQ2XnITYtQlTg41YkAP.AXUXrUWY.DPAA.C.....RkzTEAUXtUFaC8lalk1Y0IWXzk1atA..Av.akYFcCMD.ADfUgwVckAP.EDvZ.....zVZjQFakMzP.DP.VEFa0UF.ATP.sA....fbocFZzMzP.DP.VEFa0UF.ATP.uA.....akYFcP8zT.DP.VEFa0UF.Aj.A............skFYjwVYP8zT.DP.VEFa0UF.Aj.A............xk1YnQGTOME.ADfUgwVckAP.IP.............cxE1XqAWXjg0PCAP.AXUXrUWY.DPAADG.....zIWXisFbgQVVCMD.ADfUgwVckAP.EDfb.....PmbgM1ZvEFYZMzP.DP.VEFa0UF.ATP.yA.....cxE1XqAWXjgETOME.ADfUgwVckAP.IP.............cxE1XqAWXjkETOME.ADfUgwVckAP.IP.............cxE1XqAWXjoETOME.ADfUgwVckAP.IP............."
						}
,
						"snapshotlist" : 						{
							"current_snapshot" : 0,
							"entries" : [ 								{
									"filetype" : "C74Snapshot",
									"version" : 2,
									"minorversion" : 0,
									"name" : "Equator",
									"origin" : "Equator.vst",
									"type" : "VST",
									"subtype" : "Instrument",
									"embed" : 0,
									"snapshot" : 									{
										"pluginname" : "Equator.vst",
										"plugindisplayname" : "Equator",
										"pluginsavedname" : "/Library/Audio/Plug-Ins/VST/Equator.vst",
										"pluginsaveduniqueid" : 0,
										"version" : 1,
										"isbank" : 0,
										"isbase64" : 1,
										"blob" : "24488.CMlaKA....fQPMDZ....ATTbzIG...P2....A........................................7EaP.vQ+6GA..PuB..............................M2LVXhQyMwbSX4LFMlgyLhcCNyDyLzTyXy.SY1HCNjAPQQUUPT8jTeAkTEMUQTAP.DXWYxMWZu4F.AbPAw3RNt.C.0UWZjAP.hT.M2LVXhQyMwbSX4LFMlgyLhcCNyDyLzTyXy.SY1HCNjA.cgc1b.DfOE.UZg41arDzXuU2bzk1XrDDczE1XqwxTzIWcisFKBIWZmgFcrPTXxsFKRk1XnwxUgIWarb0auQFKRkzTEAvbuUmajQTZgwVRtQVY3AP.GTPKwvRKw.f.wDPSOQTSAQkTIgE..D.VC8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QAA0FbfTja1UFauAWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.D.DEDTavARQtYWYr8FbkoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNy.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QAA0FbfTja1UFauAWY5TC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.D.DEDTavARQtYWYr8FbkoiM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.UTvSyMVZrwVXz8lbfLzagI2bkoSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.UTvSyMVZrwVXz8lbfLzagI2bkoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.STvSyMVZrwVXz8lbfXTZtUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.ALQAOM2XowFagQ2axAhQo4VY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DvDE7zbikFarEFcuIGHFklakoiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.RTvTg0FbrUlbfLzagI2bkoCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTvTg0FbrUlbfXTZtUlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.AHQASEVavwVYxAxPuElbyUlNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A.QASEVavwVYxAhQo4VY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPDELUXsAGakIGHLUlckwlNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxnCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAhL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfHiNx.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxnyL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAhL5PC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfHiN0.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHxniM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.PTPPsAGHE4lckw1avUlNz.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.AjQASEVavwVYxAhQowFckIGHCUGcuYlY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPFELUXsAGakIGHFkFazUlbfLTcz8lYloSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.OTfSuk1bkABSkYWYroCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfLiNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHyniL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5LC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DfCETja1UFauAWYfLiNz.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAN8FHM8FY0wVXzk1atoCL.PVYyQG.A3PAE4lckw1avUFHynSM.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTfSuARSuQVcrEFco8la5.C.jU1bzAP.NTPQtYWYr8FbkAxL5XC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5.C.2UVZmgFc.DfAE.iKxTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOAhL5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5.C.2UVZmgFc.DfAE.iKxTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DPBEvjQOARL5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPDE3zafzzajUGagQWZu4lNv..YkMGc.DvCELUXsAGakIGHPEla5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkARL5.C.jU1bzAP.YTvTg0FbrUlbfXTZrQWYxAxP0Q2alYlNv.vckk1YnQG.AfQAv3xMwDSLwDSLxfyLy.iLy.yMwHCN4.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AvPASQmbosVYfDiNv..YkMGc.D.DEDTavARQtYWYr8FbkoCM.bWYocFZzAP.XT.LtjiLxHiLxHSM1XiMvPiMwPiL0bCN.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.LTvTzIWZqUFHxnCL.PVYyQG.AjQASEVavwVYxAhQowFckIGHCUGcuYlY5DC.2UVZmgFc.D.FE.iK2HiLxHiLxXCN0fSLyjCLyfCL3XC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkAxL5.C.jU1bzAP.NTPQtYWYr8FbkAhL5PC.2UVZmgFc.D.FE.iKzbyM2byM2bSNw.iLyHSMzLSNzTC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.CELEcxk1ZkABM5.C.jU1bzAP.STfQowFckIGHw.xP0Q2alYlNv.vckk1YnQG.AfQAv3RM0TSM0TSM3HCLzXSMvfyM3jCL1.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.ADQAKUVdzIWXisVZtcFHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroCL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.QTvRkkGcxE1XqklamAhL5.C.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DPEE7zbikFarEFcuIGHC8VXxMWY5HC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DfDELUXsAGakIGHC8VXxMWY5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DvBEbDaoQVYfDiNv..YkMGc.DfDELUXsAGakIGHC8VXxMWY5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5PC.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNz..YkMGc.DPDELUXsAGakIGHLUlckwlNw.vckk1YnQG.AfQAv3hLxHiLxHiLxLCN2bSNvXyM4jyLx.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNz..YkMGc.D.DEDTavARQtYWYr8FbkoCL.bWYocFZzAP.XT.LtPyM2byM2byM4DCLxLiL0PyL4PSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCM.PVYyQG.A3PAE4lckw1avUFHxnCL.bWYocFZzAP.XT.LtPyM2byM2byM4DCLxLiL0PyL4PSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCM.PVYyQG.A.QAA0FbfTja1UFauAWY5LC.2UVZmgFc.D.FE.iK1DSLwDSLwXCMvjyLvDyM0bCNwHC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5PC.jU1bzAP.NTPQtYWYr8FbkAhL5LC.2UVZmgFc.D.FE.iK2.CLv.CLvPyM1fyL2DSM3HCLyDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QkwVX4ABSkYWYrABSkYFc5.C.2UVZmgFc.D.FE.iK0byM2byM3.iL4PCMwfyLyPSN1DC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.WT.QkwVX4AhQkUFYhE1XqABSkYFc5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.D.FEPTYrEVdfXTYkQlXgM1ZfHUZmgFc5.C.2UVZmgFc.D.FE.iKwHiLxHiLxHiLyfyM2jCL1bSN4LC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.UT.QkwVX4ABSkYWYrAhTocFZzoCL.bWYocFZzAP.XT.LtTiLxHiLxHiLvfSN2XyMzTiMvTSM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.A.QACg1axU2bfbUZjQGZ5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5.C.jU1bzAP.NTvPn8lb0MGHWUFc5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5.C.jU1bzAP.PTvPn8lb0MGHSAWYkQlNv.vckk1YnQG.AfQAv3xL3fCN3fCN4TSMwDiMxbSL4biL2.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNw..YkMGc.DPBEvjQOAhL5DC.2UVZmgFc.DvEE.iK1HiLxHiLxPCM2LSN0LiLzbCL2.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNw..YkMGc.DPBEvjQOARL5DC.2UVZmgFc.D.FE.iK2LyLyLyLyPSNxHyM4.SMxbyLzPC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5DC.jU1bzAP.IT.SF8DHwnCL.bWYocFZzAP.ZTPKv3BLzDiM1XiM1bSNvfCMy.CL4jCM3bC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5HC.jU1bzAP.PTPPsAGHE4lckw1avUlNy.vckk1YnQG.AfQAv3hM0TSM0TSMzXiL3LyMxDSNxLCNy.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNx..YkMGc.DfCETja1UFauAWYfHiNy.vckk1YnQG.AfQAv3xMwDSLwDSLxfyLy.iLy.yMwHCN4.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.DvDEPTZyQ2axQWZu4FHFUmd5oCL.bWYocFZzAP.WT.LtDCN3fCN3fSNxTyLwLSNzjSM3TC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QoMGcuIGco8lafHDak4FY5.C.2UVZmgFc.D.FE.iK2TSM0TSM0bCLwHSM0bSN3LyL4fC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEzTXiI2a5LC.jU1bzAP.TT.QoMGcuIGco8lafPjboYWY5.C.2UVZmgFc.DvEE.iKwfCN3fCN3jiL0LSLyjCM4TCN0.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPAME1Xx8lNy..YkMGc.DvDEPTZyQ2axQWZu4FHT8lakoCL.bWYocFZzAP.XT.LtHiLxHiLxHiLyfyM2jCL1bSN4LiL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoyL.PVYyQG.APQADk1bz8lbzk1atABSkYWYroCL.bWYocFZzAP.XTPKv3hL3fCN3fSNvDCM2HCL4DiM2PCN.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.ADQASEVavwVYxABSkYWYroCL.bWYocFZzAP.XTPKv3RLzPCMzPCM0.yMyXCLzTCNybCM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.ITPSgMlbuoCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.XTPKv3RLzPCMzPCM0.yMyXCLzTCNybCM.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.PTPPsAGHE4lckw1avUlNv..YkMGc.D.EE7zbikFarEFcuIGHLUlckwlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.A.QAA0FbfTja1UFauAWY5.C.jU1bzAP.TTvSyMVZrwVXz8lbfvTY1UFa5DC.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.D.DEDTavARQtYWYr8FbkoCL.PVYyQG.APQAOM2XowFagQ2axABSkYWYroiL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.PTPPsAGHE4lckw1avUlNv..YkMGc.DPDELUXsAGakIGHLUlckwlNv.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.A3PAE4lckw1avUFHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.CTPL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.IT.SF8DHwnCL.PVYyQG.A7PASEVavwVYxABTg4lNw.vckk1YnQG.ALPAw.PagAGbo41Y.Dv.E.C..LzSN4TQCQURO4D.APvbuUmbiUF.AjPALYzSfDiNv..YkMGc.DvCELUXsAGakIGHPEla5.C.2UVZmgFc.Dv.EDC.sEFbvklamAP.CT.L..vPO4jSEMDUI8jS.D.Ay8VcxMVY.DPBEvjQOAhL5.C.jU1bzAP.QTvTg0FbrUlbfvTY1UFa5.C.2UVZmgFc.DPFEzBLtfiLxHiLxHyLxfSL3XCLyTSL0XiL.zVXvAWZtcF.ALPAv...C8jSNUzPTkzSNAP.DL2a0I2XkAP.IT.SF8DHxnCL.PVYyQG.ADQASEVavwVYxABSkYWYroSL.bWYocFZzAP.YTPKv3BNzPCMzPCM0LyMwXiL2fCL2XSL2.PagAGbo41Y.Dv.E.C..rTQYQkTAMzRI4zQ.DP.s8FYkAP.CTPL.DvAN8DQEAP.B.WZzMFZ.Dv.E.C.g01a04Fc.D.FE.iKzbCLyLCN4bCLzHiL2PCM2TCL4fC..3zSDUD.AH.boQ2XnAP.XT.LtHSNyPSM3LyMxLSMzTCL2PCM1HSN.DVauUmazAP.WT.LtLiM3XCMz.SM3bCLzLyM1HiLvbC..3zSDUD.AH.boQ2XnAP.XT.LtLiL3XCNxTSLx.CMzjCL1XSL1HSL.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AbQAv3RM3XiLy.SM2XCLyfyL1.SM4TyM.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AfQAv3hMxTSM2DCNzXSN1DSN2TCL4biM1.PXs8VctQG.AfQAv3RMzXiMw.SL2XSM1LiL1HSNyjCM0...N8DQEAP.B.WZzMFZ.D.FE.iK1byM2HSL3TCNvHCM0jyMwXyM4bC.g01a04Fc.Dv.EDC..3zSDUD.AH.boQ2XnAP.CTPL.DVauUmazAP.CTPL...TAIUPMAP.BjFY.D.CE7zTCARLLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.JTvSSMDHw.UXtAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCE7zTCARLFkFazUlbfDC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.OTvSSMDHwXTZrQWYxAhL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjPAOM0PfDiQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPCE7zTCARLRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AnPAOM0PfDCQxkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvSSMDHwbUX1UlYuIWa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A3PAOM0PfDSQtElXrUFY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAOM0PfDyPuElbyUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KTvSSMDHwXTZtUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTvSSMDHw.UcrMWYWkFYzgF.1EFa0UF.AXPAv3hL0...PEjTA0D.AHPZjAP.LTvSSMDHxvTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AnPAOM0PfHCTg4F.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvSSMDHxXTZrQWYxARL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A7PAOM0PfHiQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DPBE7zTCAhLFgE.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.MTvSSMDHxHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfBE7zTCAhLDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAOM0PfHyUgYWYl8lbsAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfCE7zTCAhLE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPCE7zTCAhLC8VXxMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ArPAOM0PfHiQo4VY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAOM0PfHCT0w1bkcUZjQGZ.XWXrUWY.DfAE.iKxTC...UPRETS.Df.oQF.AvPAOM0PfLCSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfBE7zTCAxLPEla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAOM0PfLiQowFckIGHw.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvCE7zTCAxLFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ITvSSMDHyXDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAOM0PfLiTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.JTvSSMDHyPjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCE7zTCAxLWElckY1ax0F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.NTvSSMDHyTjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.MTvSSMDHyLzagI2bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvBE7zTCAxLFklakAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDE7zTCAxLPUGayU1UoQFcnAfcgwVckAP.FT.LtHSM...TAIUPMAP.BjFY.DvBEXTSE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDEHUZtcVSuQlQowFckIGHw.fcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDEHUZtcVSuQlQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvBEHUZtcVSuQlQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCEHUZtcVSuQlTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfTo41YM8FYDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQASEVavwVYxARLE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.DELUXsAGakIGHwvTY1UFa.XWXrUWY.D.FE.iK1HyMwTSNxjyMzXiMxbCNvbiMwbC...UPRETS.Df.oQF.A3PASEVavwVYxARLPEla.XWXrUWY.DPFE.iKvPiMxfSNvfiMyPSL3TyM4DCLwTiM...TAIUPMAP.BjFY.DPDELUXsAGakIGHw7jYlMWYzAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDELUXsAGakIGHwXTZrQWYxARL.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQASEVavwVYxARLFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.MTvTg0FbrUlbfDiQXAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDELUXsAGakIGHwHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCELUXsAGakIGHwPjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDELUXsAGakIGHwLzagI2bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvCELUXsAGakIGHwXTZtUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTvTg0FbrUlbfHSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A.QASEVavwVYxAhLLUlckwF.1EFa0UF.AzPAv3xM1bSM2fSLxTC...UPRETS.Df.oQF.A3PASEVavwVYxAhLPEla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLOYlYyUFc.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQASEVavwVYxAhLFkFazUlbfDC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.STvTg0FbrUlbfHiQowFckIGHx.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DPCELUXsAGakIGHxXDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A3PASEVavwVYxAhLDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQASEVavwVYxAhLC8VXxMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PASEVavwVYxAhLFklakAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCE3zaoMWYE4VXhwVYjAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CE3zaoMWYWkFYzgF.1EFa0UF.AfQAv3hL3TCN0.yMvLyMwXiL2fCL2XSL2...PEjTA0D.AHPZjAP.LTfSuk1bkwTY1UFa.XWXrUWY.D.FE.iK4.iLzbyL4fiMwPCN3LCMxHCN0HC...UPRETS.Df.oQF.A7PAN8VZyUlQowFckIGHw.fcgwVckAP.CTPL...TAIUPMAP.BjFY.DvCE3zaoMWYFkFazUlbfHC.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ITfSuk1bkYDV.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAN8VZyUlTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.JTfSuk1bkQjb4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCEXTZrQWYxARLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPDEXTZrQWYxARLE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.DEXTZrQWYxARLCUGcOYlY.XWXrUWY.D.FE.iK4.SNxPCM2DiMwXyMzPSN4TSLwbC...UPRETS.Df.oQF.ALQAFkFazUlbfDiTkM2atElaiUF.1EFa0UF.AjQAv3BL3biM2LyLxfCNwXCN4.yMwXSM0LC...UPRETS.Df.oQF.ALQAFkFazUlbfDyPu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEXTZrQWYxARLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfEEXTZrQWYxARLC8VahYTYkQlXgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A3PAFkFazUlbfHCU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAFkFazUlbfHSQtElXrUFY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAFkFazUlbfHyP0Q2SlYF.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DvDEXTZrQWYxAhLRU1bu4VXtMVY.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.ALQAFkFazUlbfHyPu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEXTZrQWYxAhLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfEEXTZrQWYxAhLC8VahYTYkQlXgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAN8VZyUFHFkFazUlbTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPEE3zaoMWYfXTZrQWYxUjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.TTfSuk1bkAhQowFckI2P0Q2SlYF.1EFa0UF.AfQAv3BN4HSN1fyMwPiLybiLwLSLyPyM2...PEjTA0D.AHPZjAP.WTfSuk1bkAhQowFckImTkM2atElaiUF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.WTfSuk1bkAhQowFckI2Pu0lXDUFagkG.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPEE3zaoMWYfXTZrQWYxMzasIVSogG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.ZTfSuk1bkAhQowFckI2Pu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.VTvTg0FbrUlbfXTZrQWYxARLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPFELUXsAGakIGHFkFazUlbfDSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AfQASEVavwVYxAhQowFckIGHwLTcz8jYlAfcgwVckAP.XT.LtLyM4fSL2XSNzPiL0TCNxfCN0bCM...TAIUPMAP.BjFY.DvFELUXsAGakIGHFkFazUlbfDiTkM2atElaiUF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.aTvTg0FbrUlbfXTZrQWYxARLC8VahQTYrEVd.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.YTvTg0FbrUlbfXTZrQWYxARLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfGELUXsAGakIGHFkFazUlbfDyPu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.VTvTg0FbrUlbfXTZrQWYxAhLTkGbkAfcgwVckAP.CTvM...TAIUPMAP.BjFY.DPFELUXsAGakIGHFkFazUlbfHSQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AfQASEVavwVYxAhQowFckIGHxLTcz8jYlAfcgwVckAP.XT.LtfCM1DCNvTSM3HCLzXSMvfyM3jSL...TAIUPMAP.BjFY.DvFELUXsAGakIGHFkFazUlbfHiTkM2atElaiUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.aTvTg0FbrUlbfXTZrQWYxAhLC8VahQTYrEVd.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.YTvTg0FbrUlbfXTZrQWYxAhLC8Vah0TZ3AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfGELUXsAGakIGHFkFazUlbfHyPu0lXFUVYjIVXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.NT.QkwVX4UjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.KT.QkwVX4wTYlQG.1EFa0UF.AfQAv3RL2TCLv.CLwDSNx.SNxfSN0TCL3...PEjTA0D.AHPZjAP.LT.QkwVX4IUZmgFc.XWXrUWY.D.FE.iKyTCLv.CLvHyL3PSL3TyM4DCLwXC...UPRETS.Df.oQF.A3PAFUVYjIVXisFSkYFc.XWXrUWY.D.FE.iKzHiMwbSL2HCLvHyM4HyL0fyL4fC...UPRETS.Df.oQF.A7PAFUVYjIVXislTocFZzAfcgwVckAP.XT.LtHyMzLCL0TCNx.CM1TCL3bCN4.iM...TAIUPMAP.BjFY.DvBEvTY1UFaLUlYzAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CEvTY1UFaRk1YnQG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTvPn8lb0MWQtElXrUFY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A3PACg1axU2bfLEbkUFY.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.A7PACg1axU2bfDTauUmazAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfCELDZuIWcyAxUoQFcnAfcgwVckAP.ET.LtTC...UPRETS.Df.oQF.A3PACg1axU2bfPTYvQGZ.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A7PARUlckImXE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.D.CEHUY1UlbhAxUkQG.1EFa0UF.AjQAv3BL1PCNv.yLzPCMvbSM0fCMzDSL1HC...UPRETS.Df.oQF.AHQARUlckImXf.kbkABQkwVX4AfcgwVckAP.XT.LtDCM0bCN4jyL1DCNzfCNyDSL2XCN...TAIUPMAP.BjFY.D.DEHUY1UlbhABQg0Fbo41Y.XWXrUWY.D.FE.iK2fCLzXCN2XSL4HCL4HCN4TSMvfC...UPRETS.Df.oQF.AzPARUlckImXfLUZ5UF.1EFa0UF.AfQAv3RM1LyL1fCL3HCLzXSMvfyM3jCL1...PEjTA0D.AHPZjAP.KTPQQUjagIFakQF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGHw.fcgwVckAP.XT.LtDiM1XiM1XyMwXyLybiLvLSN2jSM...TAIUPMAP.BjFY.DvBETTTfbTXo4FHw.fcgwVckAP.CT.L...TAIUPMAP.BjFY.D.BETTTfDEHw.fcgwVckAP.XT.LtDSMv.CLv.CL0jiMvPiMzPyM2TCM...TAIUPMAP.BjFY.D.DETTTfXjbkEWck41X4AhL.XWXrUWY.DvEE.iKyLyLyLyLyPyLxXyMzPCL2jSM4...PEjTA0D.AHPZjAP.KTPQQAxQgklafHC.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.HTPQQARTfHC.1EFa0UF.AfQAv3RL0.CLv.CLvTSN1.CM1PCM2bSMz...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGHy.fcgwVckAP.XT.LtjCLxLSNvPiLvPyL1fSM4DyLvfiM...TAIUPMAP.BjFY.DvBETTTfbTXo4FHy.fcgwVckAP.YTPKv3hLvHyMvHyMvDCL4DyM1XyL0bCMx...PEjTA0D.AHPZjAP.HTPQQARTfLC.1EFa0UF.AfQAv3BMzDSM1HSMvLSM2XiL2fiM3XSMx...PEjTA0D.AHPZjAP.OT.SF8DHw.0arElboQWd.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.A.QALYzSfDyUgYWYSgVXvUF.1EFa0UF.ALPAz...PEjTA0D.AHPZjAP.LT.SF8DHwvTY1UFa.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QALYzSfDiQxUVb0UlaikG.1EFa0UF.AjQAv3BL3fyLzXCMvXCNwbCMyXiLwfiL1HC...UPRETS.Df.oQF.A3PALYzSfDCUxk1YmUlb.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ArPALYzSfDiQgQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PALYzSfHCTuwVXxkFc4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEvjQOAhLWElckMEZgAWY.XWXrUWY.Dv.EPC...UPRETS.Df.oQF.AvPALYzSfHCSkYWYrAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEvjQOAhLFIWYwUWYtMVd.XWXrUWY.D.FE.iKwLyLyLyLyPCLxfyMx.CN0TyMwLC...UPRETS.Df.oQF.A3PALYzSfHCUxk1YmUlb.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ArPALYzSfHiQgQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AfQAA0FbfTja1UFauAWYRUFbkEFcTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.EEDTavARQtYWYr8FbkEDczE1XqAfcgwVckAP.YT.Lt.iL2DCLvLCLvPSL1LSMvLiMzXCN0...PEjTA0D.AHPZjAP.STPPsAGHE4lckw1avUFQkMVX4AfcgwVckAP.XT.LtbyL4TiM1TCLzjSM0HSNwbCM3.SM...TAIUPMAP.BjFY.DPEEDTavARQtYWYr8FbkMUcyQWXo4F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.UTPPsAGHE4lckw1avUlTkwVYgMWY.XWXrUWY.D.FE.iKxHSN2bSMxjCM1XSL0HSL4DSL1HC...UPRETS.Df.oQF.ALQAA0FbfTja1UFauAWYLUlckwF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.aTPPsAGHE4lckw1avUFTrU2Xq8jYlwTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ArQAA0FbfTja1UFauAWYPwVcis1SlY1UoQFcnAfcgwVckAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TAIUPMAP.BjFY.DfEETja1UFauAWYfHiTkAWYgQGU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAE4lckw1avUFHxDDczE1XqAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfHCQkMVX4AfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDETja1UFauAWYfHyT0MGcgkla.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQAE4lckw1avUFHxHUYrUVXyUF.1EFa0UF.AfQAv3RL3DiL0.SL1jCN2LiLybiMvjCN1...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkAhLLUlckwF.1EFa0UF.AfQAv3hLwHiMy.iLwHyLvXSN2XyLwfyL1...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkAhLPwVcis1SlYFSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfHCTrU2Xq8jYlcUZjQGZ.XWXrUWY.DPFE.iKvjSN4jSN4PSL3fSMzbSLyPyL4jCM...TAIUPMAP.BjFY.DfEETja1UFauAWYfLiTkAWYgQGU4AWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAE4lckw1avUFHyDDczE1XqAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfLCQkMVX4AfcgwVckAP.XT.LtDCLzbCL2DCNwPSMybCLzfyLyjCN...TAIUPMAP.BjFY.DvDETja1UFauAWYfLyT0MGcgkla.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQAE4lckw1avUFHyHUYrUVXyUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkAxLLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkAxLPwVcis1SlYFSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfLCTrU2Xq8jYlcUZjQGZ.XWXrUWY.D.FE.iKw.CLv.CLv.SLzjCLwDiMwDSNyfC...UPRETS.Df.oQF.AXQAE4lckw1avUFHzHUYvUVXzQUdvUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTPQtYWYr8FbkABMAQGcgM1Z.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAE4lckw1avUFHzPTYiEVd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ALQAE4lckw1avUFHzLUcyQWXo4F.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.STPQtYWYr8FbkABMRUFakE1bkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPDETja1UFauAWYfPCSkYWYrAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DPFETja1UFauAWYfPCTrU2Xq8jYlwTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjQAE4lckw1avUFHz.Ea0M1ZOYlYWkFYzgF.1EFa0UF.AfQAv3RLv.CLv.CLvDCM4.SLwXSLwjyL3...PEjTA0D.AHPZjAP.VTPQtYWYr8FbkARMRUFbkEFcTkGbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDETja1UFauAWYfTSPzQWXisF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.QTPQtYWYr8FbkARMDU1XgkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.STPQtYWYr8FbkARMSU2bzEVZtAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DvDETja1UFauAWYfTiTkwVYgMWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQAE4lckw1avUFH0vTY1UFa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AjQAE4lckw1avUFH0.Ea0M1ZOYlYLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.YTPQtYWYr8FbkARMPwVcis1SlY1UoQFcnAfcgwVckAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TAIUPMAP.BjFY.D.GEXTZrQWYxAhPr81XqAxPu4lYocVcxEFco8la.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A7PAI4Fb0QGHw.BcuAhQXAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DvDEjjavUGcfDCHz8FHRUlckImX.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAI4Fb0QGHw.BcuABQxkG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTPRtAWczAhLfP2afXDV.XWXrUWY.DPAE.iK0...PEjTA0D.AHPZjAP.STPRtAWczAhLfP2afHUY1UlbhAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.DEjjavUGcfHCHz8FHDIWd.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQAF0DHC8lalk1Y0IWXzk1atAfcgwVckAP.CT.L...TAIUPMAP.BjFY.D.CEXTSfPTYvQGZfDD.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfQMABQkAGcnAhP.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAPIWYyMWcxUFHMEFbvklamAxPuUlY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ATQASQmbosVYfzTXvAWZtcFHC8VYlAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPFE.UZzMFZfHTYtQFHMEFbvklamAxPuUlY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QAEEEHFIWYwUWYtMVdfPC.1EFa0UF.Aj.A....fUUUk+C.PEjTA0D.AHPZjAP.KTPQQAxQgklafPC.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.HTPQQARTfPC.1EFa0UF.AfQAv3hLv.CLv.CLvHSN3.iLyHiLyfyM2...PEjTA0D.AHPZjAP.PTPQQAhQxUVb0UlaikGH0.fcgwVckAP.XT.LtbCN4TCL3XCMvbiM1DCMybSN3fyL...TAIUPMAP.BjFY.DvBETTTfbTXo4FH0.fcgwVckAP.XT.LtDyM0XyM0XyLvTiM4PSM3.CL2fSL...TAIUPMAP.BjFY.D.BETTTfDEH0.fcgwVckAP.YT.Lt.SNxjiL4XSNw.yM1HyM3XCN1TiLy...PEjTA0D.AHPZjAP.STPRtAWczARLfP2af7TczAWczAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDEjjavUGcfHCHz8FHOUGcvUGc.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQAOUGcvUGcfbVXo4FHz8FHFgE.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.WTvS0QGb0QGHmEVZtABcuAhTkYWYxIF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.TTvS0QGb0QGHmEVZtABcuABQxkG.1EFa0UF.ALPAv...PEjTA0D.ADPZjAP.ST.SoYFcfzTXvAWZtcFHC8VYlA..PEjTA0D.ADPZjAP.YT.TxU1byUmbkARSgAGbo41YfLzakYFHx...PEjTA0D.ADPZjAP.WTvTzIWZqUFHMEFbvklamAxPuUlYfHC...UPRETS.DP.oQF.ATQALklYzARSgAGbo41YfLzakYFHx...PEjTA0D.ADPZjAP.aT.ToQ2XnAhPk4FYfzTXvAWZtcFHC8VYlAhL...TAIUPMAP.AjFY.DPFE.kbkM2b0IWYfzTXvAWZtcFHC8VYlAxL...TAIUPMAP.AjFY.DvEELEcxk1ZkARSgAGbo41YfLzakYFHy...PEjTA0D.ADPZjAP.UT.SoYFcfzTXvAWZtcFHC8VYlAxL...TAIUPMAP.AjFY.DvFE.UZzMFZfHTYtQFHMEFbvklamAxPuUlYfLC...UPRETS.DP.oQF.AjQAPIWYyMWcxUFHMEFbvklamAxPuUlYfPC...UPRETS.DP.oQF.AbQASQmbosVYfzTXvAWZtcFHC8VYlABM...TAIUPMAP.AjFY.DPEEvTZlQGHMEFbvklamAxPuUlYfPC...UPRETS.DP.oQF.ArQAPkFcigFHBUlajARSgAGbo41YfLzakYFHz...PEjTA0D.AHPZjAP.NTvSiQWX1UFHSgVZlQG.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.LTfUuk1XkARSuQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.A.QARklam0zajUjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.OTfSuk1bkcUX1UlYuIWa.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.ALQABkFciIWcygVYxUjagIFakQF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.RTfPoQ2XxU2bnUlbfPjboYWY.XWXrUWY.D.FE.iKxDCMwjiL2.yLyXiMxbSN1.iLvTC...UPRETS.Df.oQF.AHQABkFciIWcygVYxAxPxU2bnAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvDEHTZzMlb0MGZkIGHRUFY0MVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.ADQABkFciIWcygVYxABUu4VY.XWXrUWY.Dv.EDC...UPRETS.Df.oQF.AHQABkFciIWcygVYxAhPrUlajAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDEHTZzMlb0MGZkIGHLUlckwF.1EFa0UF.AfQAv3RM1PyM0XSNxjCN2PCMx.SL1XCLx...PEjTA0D.AHPZjAP.ST.QoMGcuIGco8laE4VXhwVYjAfcgwVckAP.CTPL...TAIUPMAP.BjFY.DfDEPTZyQ2axQWZu4FHDIWZ1UF.1EFa0UF.ATPAv3RM...TAIUPMAP.BjFY.DPDEPTZyQ2axQWZu4FHBE1byAfcgwVckAP.ET.LtTC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atABUu4VY.XWXrUWY.D.FE.iKxTSMyfSL4PSL2jSMyPSNwHSLvjC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atAhQ0omd.XWXrUWY.D.FE.iKyDiM4TSN1PSNyHCMzDyMwDCMxXC...UPRETS.Df.oQF.ADQADk1bz8lbzk1atAhPoQWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AHQADk1bz8lbzk1atAhPrUlajAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DfDEPTZyQ2axQWZu4FHLUlckwF.1EFa0UF.ALPAw...PEjTA0D.AHPZjAP.ZTPPsAGHE4lckw1avUVPzQWXisFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.YTPPsAGHE4lckw1avUFQkMVX4AxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvFEDTavARQtYWYr8FbkIUYrUVXyUFHSw1avUF.1EFa0UF.AjQAs.iKwTSM0TSM0PiMxfyL2HSL4HyL3LC...UPRETS.Df.oQF.AfQAE4lckw1avUFHxDDczE1XqAxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DvEETja1UFauAWYfHCQkMVX4AxTr8FbkAfcgwVckAP.CT.L...TAIUPMAP.BjFY.DPFETja1UFauAWYfHiTkwVYgMWYfLEauAWY.XWXrUWY.DPFEzBLtHCMzPCMzPiL4fyMzPiLvDiM1.iL...TAIUPMAP.BjFY.D.FETja1UFauAWYfLSPzQWXisFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.WTPQtYWYr8FbkAxLDU1XgkGHSw1avUF.1EFa0UF.AjQAs.iKzHSM0LSL4HyL2bCL4.CM0PSLvHC...UPRETS.Df.oQF.AjQAE4lckw1avUFHyHUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQtYWYr8FbkABMAQGcgM1ZfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAE4lckw1avUFHzPTYiEVdfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AjQAE4lckw1avUFHzHUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQtYWYr8FbkARMAQGcgM1ZfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AbQAE4lckw1avUFH0PTYiEVdfLEauAWY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AjQAE4lckw1avUFH0HUYrUVXyUFHSw1avUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KT.UxElayA2ayUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.KTfQo4VYfPUctUF.1EFa0UF.ALPAv...PEjTA0D.AHPZjAP.XTPQlYVYiQGHM8FY0wVXzk1atARSuQVY.XWXrUWY.Dv.E.C...UPRETS.Df.oQF.AzPAPIWYyUFcLUlckwF.1EFa0UF.AfQAv3RL4LSL0XCM1TCN3fCLxLyL2XCM1...KUTVTIUPCsTRNcjL.DP.s8FYkAP.CTfL.D.AN8DQEAP.B.WZzMFZ.Dv.E.C.g01a04Fc.Dv.EDC..3zSDUD.AH.boQ2XnAP.XT.LtPCMvLCNvDCN0fCMxTSLz.yL3.SN.DVauUmazAP.CTPL..fSOQTQ.Df.vkFcigF.AfQAv3BM1TyMxTCNvjyLyTyMvfiMwfSL1.PXs8VctQG.AfQAv3RM4DSN0PCL0HCMzfiL2HyMvTCL3...N8DQEAP.B.WZzMFZ.Dv.EDC.g01a04Fc.D.FE.iK0fCLzTSN2byL0PCLzjiM3HiMwbC..rTQYQkTAMzRI4zQy....rTQYQkTAMzRI4zQz.P.Az1ajUF.ALPAx.P.C3zSDUD.AH.boQ2XnAP.CT.L.DVauUmazAP.CT.L..fSOQTQ.Df.vkFcigF.AjQAv3BLxLCMvLCL3LSNvTSM2biM0jiMvbC.g01a04Fc.Dv.E.C..3zSDUD.AH.boQ2XnAP.CTPL.DVauUmazAP.CTPL..vTTIURKUDL..P.C.0ao4Fc.Dv.XAP.CT.L.jE.ALPAv.vPuUlYlk1XoUlazAP.CT.L...TuklazAP.CfE.AfQAv3RLxLyM3XCMvPyMxfCN3jCM1TyLy.PV.Dv.E.C.C8VYlYVZikVYtQG.AfQAv3hLzHiM2XCLzjCM2.SNvDCM3jiL1...P8VZtQG.AH.V.Dv.EDC.YAP.CTPL..vTTIURKUTL..P.C.0ao4Fc.Dv.XAP.CT.L.jE.ALPAv.vPuUlYlk1XoUlazAP.CT.L...TuklazAP.CfE.AfQAv3BNwbSN1DSL0XyL1fiL0TiMwTiLy.PV.D.FE.iK2byMzfiM4HCLyTiM2TCLzfCNxfC.C8VYlYVZikVYtQG.AfQAv3BM2jSN4jSN3jiL2DSL1LSNz.CMy...P8VZtQG.AL.V.Dv.EDC.YAP.CTPL.LzakYlYoMVZk4Fc.D.FE.iKzbSN4jSN4fSNxbSLwXyL4PCLzLC..LEURkzREIC..Dv.P8VZtQG.AL.V.Dv.E.C.YAP.CT.L.LzakYlYoMVZk4Fc.D.FE.iKx.CLv.CLv.iL4fCLxLiLxLCN2bC...0ao4Fc.Dv.XAP.XT.LtXiMxXiLwLyM3fSN3XiLvXCL0PyM.jE.AfQAv3xM1bCLwTiM4TSM2DCN4jCMwPCL1.vPuUlYlk1XoUlazAP.XT.LtDCLv.CLv.CLwPSNvDSL1DSL4LCN...TuklazAP.BfE.ALPAw.PV.D.FE.iKvDyLvfSNv.CM4.CMvLSL2TyL0PC..LEURkzREMC...fPE4DQv....HTQNQTL....BUjSDIC...fPE4DQy....HURSUTVv....HURSUTVw....HURSUTVx....HURSUTVy.....kTEM0Tv.....kTEM0Tw.....kTEM0Tx.....kTEM0Ty....vTRFQEL....LkjQTEC....SIYDUx....vTRFQ0L....ME1Xx8FUuEDaoE1bSQWXzUF..DPAMEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNv.PPrkVXykDQ.DPDEHURSUDHLUlYzAhQgQVYxA..MEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNw.PPrkVXykDQ.DvDEHURSUDHMkFYjwVYfXTXjUlb..PSAAETI4zQ.Df.ME1Xx8VRDAP.ITPSgMlbuoiL.DDaoE1bIQD.AHQARkzTEAhTocFZzAhQgQVYxA..MEDTPkjSGAP.BzTXiI2aIQD.AjPAME1Xx8lNy.PPrkVXykDQ.DPEEHURSUDHPEFYffzaxkldu4FcgwF..zTPPAURNcD.AHPSgMlbukDQ.DPBEzTXiI2a5PC.AwVZgMWRDAP.STfTIMUQf.UXjAhUkIGcoMVXrA..ME1Xx8lUgwVckMG..DPAME1Xx8lNv.P.AXUXrUWY.Dv.E.C..zTXiI2a5DC.ADfUgwVckAP.CT.L..PSgMlbuoiL.DP.VEFa0UF.ALPAv...ME1Xx8lNy.P.AXUXrUWY.Dv.E.C..zTXiI2a5PC.ADfUgwVckAP.CT.L..vTA0DTLUjT..P.BzzajUGak8EL..P.AjjayQmb00VYtQG.AHPUUkDQ.DfIEfSMvDCYgYFYsXiXzLSKzHFLk0RNyXCMsD1MvjSYjgSMkcSY3.fSg0VY.DPDEjDcgwVZg41QxElajAhYlA..M8FY0wVYeEC..DP.I41bzIWcsUlazAP.BTUUIQD.AXRA3TyMlQCMhIVKgMSXxzBMlMVLsHFYzPSKzDVMhQlYwDlXlMyL.3TXsUF.ADQAIQWXrkVXtcjbg4FYfzlY...TAIUPMAP.BjFY.DPDELUXsAGakIGHw.kbkMWYzAfcgwVckAP.IP.............TAIUPMAP.BjFY.DPDELUXsAGakIGHx.kbkMWYzAfcgwVckAP.IP.............TAIUPMAP.BjFY.DPEEPTYrEVdBAUSSkmaiUjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.WT.SF8DHwHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.WT.SF8DHxHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.dTPPsAGHE4lckw1avUlPP0DHSkmaiARQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.AvQAE4lckw1avUFHxHDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.bTPQtYWYr8FbkAxLBAUSfLUdtMFHE4VXhwVYjAfcgwVckAP.IP.............TAIUPMAP.BjFY.D.GETja1UFauAWYfPiPP0DHSkmaiARQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.AvQAE4lckw1avUFH0HDTMAxT441XfTjagIFakQF.1EFa0UF.Aj.A............T8VcigFQo0VYtMWZu41bC8lalk1Y0IWXzk1atA..ADvTk41boQWZ1kFcoU1b..P.ELEcxk1ZkAP.AXUXrUWY.Dv.EDC..bDaoQVY.DP.VEFa0UF.ALPAv...SwVZjUF.ADfUgwVckAP.CTPL...TxU1byAP.AXUXrUWY.Dv.EDC..vTZlQG.ADfUgwVckAP.CTPL...TAIUPMAP.BjFY.DPJELEaoQVYfDjXy8Fa0QWYfP0afHUYrEFcoYWYfzzajUFHE4VXhwVYjAfcgwVckAP.IP.........7+..TAIUPMAP.BjFY.DfDE.kbkMWYzABTuwVdvg1atkG.1EFa0UF.Aj.A........v.D.PEjTA0D.AHPZjAP.OT.SRwTZtsVQtElXrUFY.XWXrUWY.DPBD.............UPRETS.Df.oQF.A7QAM8lauAhUuk1XkABTx81XkM2bo41YfTjagIFakQF.1EFa0UF.Aj.A............PEjTA0D.AHPZjAP.aTPSu41afX0aoMVYf.kbuMVYyMWZtcFHPEla.XWXrUWY.DPBD.........9O.zTXiI2aT81Pu4Fcx8FaMEFbvklamMG...PSPUzPu4lYocVcxEFco8la..P.JzDTEUjagIFakQF.ADfUgwVckAP.AH..MAUQME1bzUlbCgVXt4VYrAP.AXUXrUWY.DPAAD......MAUQNUWaN8FckMDZg4lakw1b.DP.VEFa0UF.ATP.O.....PSPUDTkImSuQWYPIjTg41YkAP.AXUXrUWY.DPAA.C.....MAUQME1bzUlbPIjTg41YkAP.AXUXrUWY.DPAAH......LU1YgMVdM8FYk0TcrQWZE4VXhwVYjAP.AXUXrUWY.DP.B..SkcVXikWSuQVYSklamwVY.DP.VEFa0UF.ATP.A......SkcVXikWSuQVYFklbyQ2PnElatUFa.DP.VEFa0UF.ATP.A......SkcVXikWSuQVYLE1bzMDZg4lakwF.ADfUgwVckAP.ED.D.....vTYmE1X40zajUFToQ2XnITYtQlTg41YkAP.AXUXrUWY.DPAA.C.....RkzTEAUXtUFaC8lalk1Y0IWXzk1atA..Av.akYFcCMD.ADfUgwVckAP.EDvZ.....zVZjQFakMzP.DP.VEFa0UF.ATP.sA....fbocFZzMzP.DP.VEFa0UF.ATP.uA.....akYFcP8zT.DP.VEFa0UF.Aj.A............skFYjwVYP8zT.DP.VEFa0UF.Aj.A............xk1YnQGTOME.ADfUgwVckAP.IP.............cxE1XqAWXjg0PCAP.AXUXrUWY.DPAADG.....zIWXisFbgQVVCMD.ADfUgwVckAP.EDfb.....PmbgM1ZvEFYZMzP.DP.VEFa0UF.ATP.yA.....cxE1XqAWXjgETOME.ADfUgwVckAP.IP.............cxE1XqAWXjkETOME.ADfUgwVckAP.IP.............cxE1XqAWXjoETOME.ADfUgwVckAP.IP............."
									}
,
									"fileref" : 									{
										"name" : "Equator",
										"filename" : "Equator_20190515.maxsnap",
										"filepath" : "~/repos/spectral-lab/projects/vst_loader/data",
										"filepos" : -1,
										"snapshotfileid" : "adcd95af237eeb82c263f0899fe5d83f"
									}

								}
 ]
						}

					}
,
					"text" : "vst~",
					"varname" : "vst~[1]",
					"viewvisibility" : 0
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Arial",
					"fontsize" : 13.0,
					"id" : "obj-4",
					"maxclass" : "message",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 239.0, 120.0, 70.0, 23.0 ],
					"text" : "wclose"
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Arial",
					"fontsize" : 13.0,
					"id" : "obj-15",
					"maxclass" : "message",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 239.0, 82.0, 70.0, 23.0 ],
					"text" : "open"
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Arial",
					"fontsize" : 13.0,
					"id" : "obj-12",
					"maxclass" : "message",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 239.0, 47.0, 70.0, 23.0 ],
					"text" : "plug"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-2",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 8,
					"outlettype" : [ "", "", "", "int", "int", "", "int", "" ],
					"patching_rect" : [ 52.0, 257.0, 92.5, 22.0 ],
					"text" : "midiparse"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-18",
					"maxclass" : "newobj",
					"numinlets" : 2,
					"numoutlets" : 2,
					"outlettype" : [ "", "" ],
					"patching_rect" : [ 52.0, 150.0, 81.0, 22.0 ],
					"text" : "route track_id"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-19",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 52.0, 117.0, 143.0, 22.0 ],
					"saved_object_attributes" : 					{
						"filename" : "js-index.js",
						"parameter_enable" : 0
					}
,
					"text" : "js js-index.js autowatch 1"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-20",
					"maxclass" : "message",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 52.0, 81.0, 75.0, 22.0 ],
					"text" : "get_track_id"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-14",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 161.0, 257.0, 82.0, 22.0 ],
					"text" : "print received"
				}

			}
 ],
		"lines" : [ 			{
				"patchline" : 				{
					"destination" : [ "obj-35", 0 ],
					"source" : [ "obj-12", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-35", 0 ],
					"source" : [ "obj-15", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-6", 0 ],
					"source" : [ "obj-18", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-18", 0 ],
					"source" : [ "obj-19", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-35", 0 ],
					"source" : [ "obj-2", 7 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 0 ],
					"source" : [ "obj-20", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-10", 1 ],
					"source" : [ "obj-35", 1 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-10", 0 ],
					"source" : [ "obj-35", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-35", 0 ],
					"source" : [ "obj-4", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-14", 0 ],
					"order" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-2", 0 ],
					"order" : 1,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-20", 0 ],
					"source" : [ "obj-8", 0 ]
				}

			}
 ],
		"parameters" : 		{
			"obj-35" : [ "vst~[1]", "vst~[1]", 0 ],
			"parameterbanks" : 			{

			}

		}
,
		"dependency_cache" : [ 			{
				"name" : "js-index.js",
				"bootpath" : "~/repos/spectral-lab/projects/vst_loader/code",
				"patcherrelativepath" : "../code",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "Equator_20190515.maxsnap",
				"bootpath" : "~/repos/spectral-lab/projects/vst_loader/data",
				"patcherrelativepath" : "../data",
				"type" : "mx@s",
				"implicit" : 1
			}
, 			{
				"name" : "receiver.maxpat",
				"bootpath" : "~/repos/spectral-lab/common",
				"patcherrelativepath" : "../../../common",
				"type" : "JSON",
				"implicit" : 1
			}
 ],
		"autosave" : 0
	}

}
